### ISSUE TITLE
Falhas ao usar o Fork Queue do GitHub

### ISSUE THREAD

**Issue by carlosdelfino** [lucianosousa/git-na-pratica#11]
Nestes últimos commits observei que está havendo falhas ao se usar a opção Fork Queue.

Em todas as tentativas que fiz algo deu errado.

Em algumas nada acontece, ele fica processando indefinidamente. Em outras ele apresenta apenas uma lista de Commits que irão dar problemas durante o merge e não lista os que serão bem sucedidos, em uma delas que executei selecionando todos os commits para merge, apagou o meu branch master.

Neste momento estou observando que existem commits mais novos, mas como tive que reconstruir o meu branch master, devo ter feito algo errado que o mesmo ficou confuso e defasado, porem com data mais atual.

Alguem teria alguma sugestão para corrigir este problema?

**Comment by dukex** [comment]
sobre o Fork Queue não sei o que é, na verdade não sei nem o que faz isso de verdade.

Sobre os commits estarem confuso isso acontece quando voce da <code>git pull</code>, eu não uso o pull por que acho que ele zua a arvore, uso <code>git fetch origin</code> e depois <code>git rebase origin/master</code>, caso meu servidor remote for o origin e o branch for o master

**Comment by carlosdelfino** [comment]
entedi, realmente parece ser bem melhor, vou estudar mais o funcionamento do rebase.

Estou agora trabalhando em outro tutorial que é uma continuação deste do Submodulo porem com maior foco no Eclipse e no Egit, preciso seguir esta sequencia devido aos estudos do Framework Nooku com Joomla. 

Como talvez este tutorial sai bastante do foco exclusivo no GIT, vou faze-lo num projeto especifico do Framework, e o que for interessante espelho no Git_na_pratica.

Abraços

**Comment by lucianosousa** [comment]
resolvido e fechado
