### ISSUE TITLE
Desenrolando sua página no Git HUB

### ISSUE THREAD

**Issue by carlosdelfino** [lucianosousa/git-na-pratica#12]
Não sei se posso dizer que o GitHub não é foco no Git_na_pratica, mas queria propor um capitulo sobre a criação de página (home page) do projeto usando o GIT para gerenciar.

Na minha opinião eles deveriam ter feito algo mais integrado com o Wiki, mas já que não fizeram vou por aqui. Estaria adiantando este capitulo para o próximo fim de semana.

Como criei minha humilde página, e muitos estão fazendo isto, gostaria de propor este capitulo também, assim mostramos mais uma faceta do uso do Git e sua integração com um site de repositórios. Até o momento o GitHub me parece o mais rico em se tratando de integração, mas o Assembla também está começando a se integrar o Git e teremos novidades interessantes nesta corrida.

**Comment by lucianosousa** [comment]
eu criei uma página umas semanas atrás.
está feijão com arroz mas tá valendo.

manda ver nesse tópico. :)
abs.

**Comment by carlosdelfino** [comment]
opa, vou mandar, é bem facinho criar, talvez para um leio o dificil é assimilar a transformação.

Vou ver se faço focando no uso daquele software para montar um Forum.

Agora acho que deve rolar algum segredo interessante nestas páginas, porque ela é pre processada antes de ser liberada.

Mas as aulas começaram aqui no colégio e to cheio de serviço, pois cuido do site deles.

**Comment by lucianosousa** [comment]
No projeto tem um branch so para a pagina. Da uma olhada em como funciona que nem tem erro.
Abs

**Comment by carlosdelfino** [comment]
eu já fiz, criei alguns: http://polimig.github.com onde trabalho, o meu carlosdelfino.github.com e vou fazer do workshop em PHP que estou preparando.

Fazer a página é fácil, quero antes descobrir algum segredo ou macete mais avançado para ficar mais atraente.

Agora eu to é garrado em colocar meu fork sincronizado com o original, isto é fundamental nos projetos que trabalho e preciso ter mais sucesso nisto.
