### ISSUE TITLE
Instalação do windows, inserir imagens

### ISSUE THREAD

**Issue by maurogeorge** [lucianosousa/git-na-pratica#15]
O que acha de na instalação do windows inserir as imagens de exibição das telas? Poderiamos utilizar as imagens que estão [na documentação do github](http://help.github.com/win-set-up-git/). No link ainda possui mais informações da instalação no windows.

**Comment by lucianosousa** [comment]
Faz isso e sobe em um commit só. Fica mais explicativo, e a idéia é essa mesmo!
;)

abs.

**Comment by maurogeorge** [comment]
Pode fechar isso aqui

**Comment by lucianosousa** [comment]
vê o lance das imagens....

**Comment by maurogeorge** [comment]
Acho que devemos decidir qual padrão usar.

Pois segui o modo que estava no arquivo 30.submodulo.md se formos mudar devemos mudar em todas as ocorrências.
