### ISSUE TITLE
Fechando a primeira parte do Projeto

### ISSUE THREAD

**Issue by dukex** [lucianosousa/git-na-pratica#18]
Temos 5 topicos
1. O que é o Git e para que serve;
2. Instalando e configurando o Git (OSX, Linux e Windows);
3. Criação de um repositório local, adição de arquivos e primeiro commit;
4. Adicionando um repositório remoto e enviando as coisas para lá;
5. Usando o git no dia a dia.
   05.1 Removendo tracked files

Acho que devemos focar neles para terminar a primeira parte do projeto, não parece muita coisa.
Vou tirar um tempo para revisar e ir fechando os topicos ok, por posto aqui, quem quiser fazer o mesmo, fica a vontade

**Comment by carlosdelfino** [comment]
Ótimo, inclusive o tópico 3, eu já estava pensando nele para o github e assembla, e esta semana eu vi o pessoal do sourceforge já está adotando o git.

**Comment by dukex** [comment]
só entendi que voce estava pensando no topico 3.
não entendi o restante.

**Comment by lucianosousa** [comment]
huahuahuahuahuahua

alguém aí pode arrumar o lance do windows??
telas?

**Comment by carlosdelfino** [comment]
Digo Tópico 4, ou seja, trabalhando com repositórios Remotos. 

Já estava trabalhando peculiaridades do GitHub, como por exemplo Wiki e Pages, já no SorceForge ainda não sei o que eles tem de peculiar, estou pesquisando.

Como alguns recursos que preciso documentar vão além do Dia a Dia, estou colocando em capítulos mais a frente.

**Comment by dukex** [comment]
É isso que eu disse cara, a idéia é focar no git na pratica e não criar tópicos futuros, se não nunca sai o matéria que queremos inicialmente

**Comment by carlosdelfino** [comment]
Concordo Emerson, porem só posso dedicar a tópicos que são demanda de minha equipe no momento. Porem quero muito contribuir com seu projeto e espero chegarmos em breve num denominador comum.

Conforme possível vou dando uma olhada, e vejo no que posso postar direto no seu original.

**Comment by carlosdelfino** [comment]
Fiz uma sugestão sobre os problemas das telas diretamente no link: https://github.com/lucianosousa/git_na_pratica/blob/master/02.instalacao.md

**Comment by carlosdelfino** [comment]
Que tal retomarmos esta discussão usando o novo repositório? https://github.com/git-na-pratica/git-na-pratica/issues/

Abrindo um novo Issue para cada tópico.
