### ISSUE TITLE
Reserva do Link http://gitnapratica.github.com

### ISSUE THREAD

**Issue by carlosdelfino** [lucianosousa/git-na-pratica#19]
Sugiro que seja criado um projeto de nome git_na_pratica.github.com ou gitnapratica.github.com para que tenhamos uma URL: http://gitnapratica.github.com evitando assim que outro o faça e percamos o link.

É importante salientar que precisamos criar uma organização com este nome, e nesta criarmos tal projeto.

**Comment by lucianosousa** [comment]
criado.

nova organização: https://github.com/git-na-pratica
novo repositório: https://github.com/git-na-pratica/git-na-pratica
novo repositório para site: https://github.com/git-na-pratica/git-na-pratica.github.com

notem que renomeei o projeto.
passaremos a utilizar o branch/repo remoto de lá.

**Comment by carlosdelfino** [comment]
Vou criar a base do Jekyll, ai quem tem melhores condições para desenvolver graficamente o projeto pode mandar ver na pasta layout. pode ser assim?

O ideal seria fazermos um merge do git-na-pratica para git-na-pratica.github.com de forma a este refletir o ultimo release aprovado. O que acham?
