### ISSUE TITLE
Git: adicionar arquivos ao commit anterior  

### ISSUE THREAD

**Issue by lucascaton** [lucianosousa/git-na-pratica#21]
Seria legal inserir isso, né?!

http://erichkist.wordpress.com/2010/08/18/git-adicionar-arquivos-ao-commit-anterior/

(Vou tentar incluir, mas não posso prometer tão já, tá fogo aqui...)

[]s!

**Comment by lucianosousa** [comment]
ae lucas, altera seu branch aí, agora é esse:
https://github.com/git-na-pratica/git-na-pratica
