### ISSUE TITLE
Links para uso de markdown

### ISSUE THREAD

**Issue by lucianosousa** [lucianosousa/git-na-pratica#3]
se alguém tiver algum link para edição de texto em markdown coloca aí, vai auxiliar a galera. eu por exemplo ainda não domino isso.

**Comment by lucianosousa** [comment]
http://daringfireball.net/projects/markdown/syntax

**Comment by lucascaton** [comment]
Esse link que o Luciano Sousa mandou contém a sintaxe oficial :)
