### ISSUE TITLE
Sites para testar marcação

### ISSUE THREAD

**Issue by lucianosousa** [lucianosousa/git-na-pratica#8]
pessoal, qual a melhor forma pra testar a marcação?
fiz uns commits aqui mas algumas coisas estavam mal desenhadas e tal... daí tive que fazer outros commits para corrigir... alguém tem alguma sugestão?

abs.

**Comment by dukex** [comment]
Existe o markdown2, transforma markdown em pdf 
tenho uma função no meu vimfile que faz isso, eu passo o comando :mm ele gera um PDF, dai tenho um preview

https://github.com/emersonvinicius/vimdir/blob/master/vimrc#L98

**Comment by lucascaton** [comment]
Tem tbm um framework do Fnando: https://github.com/fnando/kitabu

Description: A framework for creating e-books from Markdown/Textile text markup using Ruby. Using the Prince PDF generator, you'll be able to get high quality PDFs.

**Comment by lucianosousa** [comment]
essa parte de pdf não tá me agradando... acho um passo desnecessário...
ontem eu começei a fazer um negócio no sinatra que atendeu +- bem...
https://github.com/lucianosousa/view-markdown
